import { createApp } from "vue";
import App from "./App.vue";
import router from "@/router/index.js";
import "./assets/css/tailwindcss.css";
import "galmuri/dist/galmuri.css";
import { pinia, piniaPluginPersistedstate } from "@/store/pinia.js";
const app = createApp(App);
app.use(router);
pinia.use(piniaPluginPersistedstate);
app.use(pinia);
app.mount("#app");
